### ISSUE TITLE
Problem with glyphicons -> dependency on bootstrap

### ISSUE THREAD

**Issue by Martinsos** [patternfly/patternfly-3#37]
In patternfly.css, glyphicons are fetched from components/ directory:

```
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url('../../components/bootstrap/dist/fonts/glyphicons-halflings-regular.eot');
  src: url('../../components/bootstrap/dist/fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('../../components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff') format('woff'), url('../../components/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('../../components/bootstrap/dist/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
}
```

Problem is that components directory is not stated anywhere as dependency, and you also say that patternfly does not depend on bootstrap, which seems incorrect from this.
I expect everything important to be in dist, so when building my web application which does minification and similat operations I get an error because I had no reason to know that stuff from components directory has to be copied.

**Comment by rhamilto** [comment]
Thank you for the feedback, @Martinsos.  I've updated the README with a section regarding the dependencies.  https://github.com/patternfly/patternfly/blob/master/README.md#dependencies

**Comment by Martinsos** [comment]
@rhamilto Thank you for quick response! I am afraid stating dependencies in README does not really solve the problem: since patternfly is a bower package, it is important that all dependencies are stated correctly, because that is expected behavior. I wanted to use it through bower, however it does not make much sense to use it that way if I have to install/include all dependencies by myself and take care that I do not include them twice: also, many tools like gulp and grunt plugins expect dependencies to be stated correctly in bower and this breaks the normal usage of this plugins. So it is important that you put dependencies correctly regarding bower!

**Comment by rhamilto** [comment]
@Martinsos Thanks for the feedback!  I'm not sure I entirely follow you.  Installation via Bower _does_ include the `components` directory.  What am I missing?

**Comment by Martinsos** [comment]
Yes it does, but that is not how bower packages should import their
dependencies. Dependencies should be stated in bower.json and then included
by bower and positioned on the same level as patternfly, in
bower_components.
Why is it a problem if they are not included that way? Let's say there is
another bower package that depends on bootstrap. Bower will install
bootstrap to bower_components, but patternfly will also download it to its
components and you will include bootstrap twice, or have to take special
care you do not include it twice.
Also, it makes problem for gulp and grunt plugins because they do not
expect code in /components to be used in production (because those are dev
dependencies so they are by definition not used in production) and when
building app for production that code will not be included.

**Comment by rhamilto** [comment]
Thank you for the clarification, @Martinsos!  I understand adding the dependencies to the repo may not be a Bower best practice, but it's necessary for the ways in which we use and distribute PatternFly (we rebrand it in a Red Hat-specific way and also distribute it as an RPM).  Like most things, we're trying to strike a balance between doing it "right" and trying to make things easy on ourselves.  It's a give and take.

**Comment by Martinsos** [comment]
I understand that, by why don't you also state this dependencies in
bower.json? You can still have stuff that you put in components. I
understand your trade off, but if you are creating a bower package of it
than you should take care it is correctly defined and works as expected, or
you should not publish it as bower package.
What I am suggesting that you just state dependencies in bower package and
that is it: then it will make sense to use it through bower, otherwise not
really.
